#!/usr/bin/env bash
# custom http hearder for web-01

# updatinh packages before installation
sudo apt-get update
sudo apt-get install -y nginx

# creating and index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# perfoming a "moved permanently redirection" (301)
new_string="listen 80 default_server;\\n\\tlocation \/redirect_me {\\n\\t\\treturn 301 https:\/\/github.com\/Cynthia-mbesa\/;\\n\\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# creating a 404 custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

new_string2="http {\\n\\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$new_string2/" /etc/nginx/nginx.conf

# testing configurations for syntax errors
sudo nginx -t

#restarting nginx after implementing changes
sudo service nginx restart
