#!/usr/bin/env bash
#Bash script that stops 4-to_infinity_and_beyond process
while true; do
echo "To infinity and beyong"
sleep 1
done &
bg_pid=$!
trap 'echo' "Terminated"; kill "$bg_pid"; exit' SIGINT
while true; do
sleep 1
done
